### ISSUE TITLE
你好下载后在微信开发工具中打开发现有bug

### ISSUE THREAD

**Issue by ZYYZhai** [1417766861/rent_mina#2]
在publish-disscuss-preview.js这个文件中 反复出现“应为标识符” “应为声明或语句” “应为’,'"这三个错误

**Comment by RelaxedDong** [comment]
开发者工具是最新的吗？可能是我的开发者工具没更新原因

**Comment by ZYYZhai** [comment]
应该是的，我电脑上的微信开发者工具是3月25日在官网上下载的稳定版。请问出现了这些bug该怎么解决呢？我搜索了一下， bug该怎么解决网络上几乎没有人回答。

发件人: puc_dong
发送时间: 2020年4月8日 17:49
收件人: 1417766861/rent_mina
抄送: N-owl; Author
主题: Re: [1417766861/rent_mina] 你好下载后在微信开发工具中打开发现有bug (#2)

开发者工具是最新的吗？可能是我的开发者工具没更新原因
