### ISSUE TITLE
请问有后端代码吗？

### ISSUE THREAD

**Issue by linhuisheng** [1417766861/rent_mina#3]
请问有后端代码吗？能分享一下吗？

**Comment by RelaxedDong** [comment]
后期公布

**Comment by wufengdkf** [comment]
@1417766861 请问一下 您的项目后台是用python语言吗

**Comment by RelaxedDong** [comment]
django



---原始邮件---
发件人: "wufengdkf"<notifications@github.com&gt;
发送时间: 2020年5月20日(周三) 上午10:58
收件人: "1417766861/rent_mina"<rent_mina@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"puc_dong"<1417766861@qq.com&gt;;
主题: Re: [1417766861/rent_mina] 请问有后端代码吗？ (#3)




 
@1417766861 请问一下 您的项目后台是用python语言吗

**Comment by wufengdkf** [comment]
@1417766861 thinks 期待

**Comment by jieshao25** [comment]
你好，大佬，有管理端代码吗？感谢

**Comment by xiaoerlaigeid** [comment]
想问下后台代码提供了吗？

**Comment by jieshao25** [comment]
没有。他说不开源



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1417766861/rent_mina"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月27日(星期天) 下午5:01
收件人:&nbsp;"1417766861/rent_mina"<rent_mina@noreply.github.com&gt;;
抄送:&nbsp;"霄源房产"<1657102740@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [1417766861/rent_mina] 请问有后端代码吗？ (#3)





 
想问下后台代码提供了吗？

**Comment by 1417766861** [comment]
![image](https://user-images.githubusercontent.com/38744096/97789119-cec83a00-1bf8-11eb-9bcc-a6c54966642d.png)
process：无用板块代码删除完成，部署文档完成，API 测试相关ing.

**Comment by fuxiong1** [comment]
hello，请问有后端的代码分享吗？谢谢哈

**Comment by RelaxedDong** [comment]
https://github.com/RelaxedDong/go_rent
